FROM mcr.microsoft.com/devcontainers/javascript-node:1-22-bullseye

# Install additional global packages if needed
# RUN npm install -g <package-name>

# Set any additional environment variables
# ENV NODE_ENV=development 